2022-12-14 00:15:25 ERROR    LexToken(COLNAME,'sadsa',1,0)
2022-12-14 00:15:34 ERROR    ssss is not supported datasource type
Traceback (most recent call last):
  File "D:\sharaf\ETLV2\app\Controllers\controllers.py", line 26, in execute
    exec(str(code))
  File "<string>", line 3, in <module>
  File "D:\sharaf\ETLV2\app\etl\core.py", line 10, in extract
    data_source:IDataSource = DataSourceFactory.createDataSource(data_source)
  File "D:\sharaf\ETLV2\app\etl\DataSources\factory.py", line 14, in createDataSource
    Type=cls._determineType(data_source)
  File "D:\sharaf\ETLV2\app\etl\DataSources\factory.py", line 55, in _determineType
    raise ValueError(T+" is not supported datasource type")
ValueError: ssss is not supported datasource type
2022-12-14 00:16:37 ERROR    sss is not supported datasource type
2022-12-14 00:20:44 INFO     Data source type is: Flatfile
2022-12-14 00:20:44 ERROR    [Errno 2] No such file or directory: 'aaa'
Traceback (most recent call last):
  File "D:\sharaf\ETLV2\app\Controllers\controllers.py", line 26, in execute
    exec(str(code))
  File "<string>", line 3, in <module>
  File "D:\sharaf\ETLV2\app\etl\core.py", line 12, in extract
    data = data_source.extract(file_path)
  File "D:\sharaf\ETLV2\app\etl\DataSources\Flatfile\Flatfile.py", line 26, in extract
    return self.extractCallbacks[self.type](file_path)
  File "D:\sharaf\ETLV2\app\etl\DataSources\Flatfile\Flatfile.py", line 11, in <lambda>
    EFlatfile.CSV: (lambda path: pd.read_csv(path)),
  File "C:\Users\server\anaconda3\envs\tf\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\server\anaconda3\envs\tf\lib\site-packages\pandas\io\parsers\readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\server\anaconda3\envs\tf\lib\site-packages\pandas\io\parsers\readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Users\server\anaconda3\envs\tf\lib\site-packages\pandas\io\parsers\readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "C:\Users\server\anaconda3\envs\tf\lib\site-packages\pandas\io\parsers\readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "C:\Users\server\anaconda3\envs\tf\lib\site-packages\pandas\io\parsers\c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "C:\Users\server\anaconda3\envs\tf\lib\site-packages\pandas\io\parsers\base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "C:\Users\server\anaconda3\envs\tf\lib\site-packages\pandas\io\common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: 'aaa'
2022-12-14 23:16:39 INFO     Extract Data source type is: Media
2022-12-14 23:16:39 INFO     Load Data distination type is: Flatfile
2022-12-14 23:42:31 INFO     Extract Data source type is: Media
2022-12-14 23:42:31 ERROR    1.0
Traceback (most recent call last):
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\Controllers\controllers.py", line 26, in execute
    exec(str(code))
  File "<string>", line 3, in <module>
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\core.py", line 12, in extract
    data = data_source.extract(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\DataSources\Media\Media.py", line 9, in extract
    data = BirdMoveDetect().get_changes(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\BirdMoveDetect.py", line 39, in get_changes
    changes_arr = motion.process_frames(framesPath)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 25, in process_frames
    return self.get_motion_per_time(dict_frame_time)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 82, in get_motion_per_time
    result[dict_pose_startTime[birdPart]][birdPart]:delta
KeyError: 1.0
2022-12-14 23:42:35 INFO     Extract Data source type is: Media
2022-12-14 23:42:35 ERROR    1.0
Traceback (most recent call last):
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\Controllers\controllers.py", line 26, in execute
    exec(str(code))
  File "<string>", line 3, in <module>
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\core.py", line 12, in extract
    data = data_source.extract(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\DataSources\Media\Media.py", line 9, in extract
    data = BirdMoveDetect().get_changes(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\BirdMoveDetect.py", line 39, in get_changes
    changes_arr = motion.process_frames(framesPath)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 25, in process_frames
    return self.get_motion_per_time(dict_frame_time)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 82, in get_motion_per_time
    result[dict_pose_startTime[birdPart]][birdPart]:delta
KeyError: 1.0
2022-12-14 23:42:37 INFO     Extract Data source type is: Media
2022-12-14 23:42:37 ERROR    1.0
Traceback (most recent call last):
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\Controllers\controllers.py", line 26, in execute
    exec(str(code))
  File "<string>", line 3, in <module>
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\core.py", line 12, in extract
    data = data_source.extract(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\DataSources\Media\Media.py", line 9, in extract
    data = BirdMoveDetect().get_changes(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\BirdMoveDetect.py", line 39, in get_changes
    changes_arr = motion.process_frames(framesPath)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 25, in process_frames
    return self.get_motion_per_time(dict_frame_time)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 82, in get_motion_per_time
    result[dict_pose_startTime[birdPart]][birdPart]:delta
KeyError: 1.0
2022-12-14 23:42:38 INFO     Extract Data source type is: Media
2022-12-14 23:42:38 ERROR    1.0
Traceback (most recent call last):
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\Controllers\controllers.py", line 26, in execute
    exec(str(code))
  File "<string>", line 3, in <module>
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\core.py", line 12, in extract
    data = data_source.extract(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\DataSources\Media\Media.py", line 9, in extract
    data = BirdMoveDetect().get_changes(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\BirdMoveDetect.py", line 39, in get_changes
    changes_arr = motion.process_frames(framesPath)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 25, in process_frames
    return self.get_motion_per_time(dict_frame_time)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 82, in get_motion_per_time
    result[dict_pose_startTime[birdPart]][birdPart]:delta
KeyError: 1.0
2022-12-14 23:42:39 INFO     Extract Data source type is: Media
2022-12-14 23:42:39 ERROR    1.0
Traceback (most recent call last):
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\Controllers\controllers.py", line 26, in execute
    exec(str(code))
  File "<string>", line 3, in <module>
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\core.py", line 12, in extract
    data = data_source.extract(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\DataSources\Media\Media.py", line 9, in extract
    data = BirdMoveDetect().get_changes(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\BirdMoveDetect.py", line 39, in get_changes
    changes_arr = motion.process_frames(framesPath)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 25, in process_frames
    return self.get_motion_per_time(dict_frame_time)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 82, in get_motion_per_time
    result[dict_pose_startTime[birdPart]][birdPart]:delta
KeyError: 1.0
2022-12-14 23:42:39 INFO     Extract Data source type is: Media
2022-12-14 23:42:39 ERROR    1.0
Traceback (most recent call last):
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\Controllers\controllers.py", line 26, in execute
    exec(str(code))
  File "<string>", line 3, in <module>
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\core.py", line 12, in extract
    data = data_source.extract(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\DataSources\Media\Media.py", line 9, in extract
    data = BirdMoveDetect().get_changes(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\BirdMoveDetect.py", line 39, in get_changes
    changes_arr = motion.process_frames(framesPath)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 25, in process_frames
    return self.get_motion_per_time(dict_frame_time)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 82, in get_motion_per_time
    result[dict_pose_startTime[birdPart]][birdPart]:delta
KeyError: 1.0
2022-12-14 23:42:39 INFO     Extract Data source type is: Media
2022-12-14 23:42:39 ERROR    1.0
Traceback (most recent call last):
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\Controllers\controllers.py", line 26, in execute
    exec(str(code))
  File "<string>", line 3, in <module>
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\core.py", line 12, in extract
    data = data_source.extract(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\DataSources\Media\Media.py", line 9, in extract
    data = BirdMoveDetect().get_changes(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\BirdMoveDetect.py", line 39, in get_changes
    changes_arr = motion.process_frames(framesPath)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 25, in process_frames
    return self.get_motion_per_time(dict_frame_time)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 82, in get_motion_per_time
    result[dict_pose_startTime[birdPart]][birdPart]:delta
KeyError: 1.0
2022-12-14 23:42:41 INFO     Extract Data source type is: Media
2022-12-14 23:42:41 ERROR    1.0
Traceback (most recent call last):
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\Controllers\controllers.py", line 26, in execute
    exec(str(code))
  File "<string>", line 3, in <module>
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\core.py", line 12, in extract
    data = data_source.extract(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\DataSources\Media\Media.py", line 9, in extract
    data = BirdMoveDetect().get_changes(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\BirdMoveDetect.py", line 39, in get_changes
    changes_arr = motion.process_frames(framesPath)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 25, in process_frames
    return self.get_motion_per_time(dict_frame_time)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 82, in get_motion_per_time
    result[dict_pose_startTime[birdPart]][birdPart]:delta
KeyError: 1.0
2022-12-14 23:42:41 INFO     Extract Data source type is: Media
2022-12-14 23:42:41 ERROR    1.0
Traceback (most recent call last):
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\Controllers\controllers.py", line 26, in execute
    exec(str(code))
  File "<string>", line 3, in <module>
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\core.py", line 12, in extract
    data = data_source.extract(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\DataSources\Media\Media.py", line 9, in extract
    data = BirdMoveDetect().get_changes(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\BirdMoveDetect.py", line 39, in get_changes
    changes_arr = motion.process_frames(framesPath)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 25, in process_frames
    return self.get_motion_per_time(dict_frame_time)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 82, in get_motion_per_time
    result[dict_pose_startTime[birdPart]][birdPart]:delta
KeyError: 1.0
2022-12-14 23:42:41 INFO     Extract Data source type is: Media
2022-12-14 23:42:41 ERROR    1.0
Traceback (most recent call last):
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\Controllers\controllers.py", line 26, in execute
    exec(str(code))
  File "<string>", line 3, in <module>
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\core.py", line 12, in extract
    data = data_source.extract(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\DataSources\Media\Media.py", line 9, in extract
    data = BirdMoveDetect().get_changes(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\BirdMoveDetect.py", line 39, in get_changes
    changes_arr = motion.process_frames(framesPath)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 25, in process_frames
    return self.get_motion_per_time(dict_frame_time)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 82, in get_motion_per_time
    result[dict_pose_startTime[birdPart]][birdPart]:delta
KeyError: 1.0
2022-12-14 23:42:44 INFO     Extract Data source type is: Media
2022-12-14 23:42:44 ERROR    1.0
Traceback (most recent call last):
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\Controllers\controllers.py", line 26, in execute
    exec(str(code))
  File "<string>", line 3, in <module>
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\core.py", line 12, in extract
    data = data_source.extract(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\DataSources\Media\Media.py", line 9, in extract
    data = BirdMoveDetect().get_changes(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\BirdMoveDetect.py", line 39, in get_changes
    changes_arr = motion.process_frames(framesPath)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 25, in process_frames
    return self.get_motion_per_time(dict_frame_time)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 82, in get_motion_per_time
    result[dict_pose_startTime[birdPart]][birdPart]:delta
KeyError: 1.0
2022-12-14 23:42:45 INFO     Extract Data source type is: Media
2022-12-14 23:42:45 ERROR    1.0
Traceback (most recent call last):
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\Controllers\controllers.py", line 26, in execute
    exec(str(code))
  File "<string>", line 3, in <module>
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\core.py", line 12, in extract
    data = data_source.extract(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\DataSources\Media\Media.py", line 9, in extract
    data = BirdMoveDetect().get_changes(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\BirdMoveDetect.py", line 39, in get_changes
    changes_arr = motion.process_frames(framesPath)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 25, in process_frames
    return self.get_motion_per_time(dict_frame_time)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 82, in get_motion_per_time
    result[dict_pose_startTime[birdPart]][birdPart]:delta
KeyError: 1.0
2022-12-14 23:42:45 INFO     Extract Data source type is: Media
2022-12-14 23:42:45 ERROR    1.0
Traceback (most recent call last):
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\Controllers\controllers.py", line 26, in execute
    exec(str(code))
  File "<string>", line 3, in <module>
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\core.py", line 12, in extract
    data = data_source.extract(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\DataSources\Media\Media.py", line 9, in extract
    data = BirdMoveDetect().get_changes(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\BirdMoveDetect.py", line 39, in get_changes
    changes_arr = motion.process_frames(framesPath)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 25, in process_frames
    return self.get_motion_per_time(dict_frame_time)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 82, in get_motion_per_time
    result[dict_pose_startTime[birdPart]][birdPart]:delta
KeyError: 1.0
2022-12-14 23:43:02 INFO     Extract Data source type is: Media
2022-12-14 23:43:02 ERROR    1.0
Traceback (most recent call last):
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\Controllers\controllers.py", line 26, in execute
    exec(str(code))
  File "<string>", line 3, in <module>
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\core.py", line 12, in extract
    data = data_source.extract(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\DataSources\Media\Media.py", line 9, in extract
    data = BirdMoveDetect().get_changes(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\BirdMoveDetect.py", line 39, in get_changes
    changes_arr = motion.process_frames(framesPath)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 25, in process_frames
    return self.get_motion_per_time(dict_frame_time)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 82, in get_motion_per_time
    result[dict_pose_startTime[birdPart]][birdPart]:delta
KeyError: 1.0
2022-12-14 23:43:04 INFO     Extract Data source type is: Media
2022-12-14 23:43:04 ERROR    1.0
Traceback (most recent call last):
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\Controllers\controllers.py", line 26, in execute
    exec(str(code))
  File "<string>", line 3, in <module>
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\core.py", line 12, in extract
    data = data_source.extract(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\DataSources\Media\Media.py", line 9, in extract
    data = BirdMoveDetect().get_changes(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\BirdMoveDetect.py", line 39, in get_changes
    changes_arr = motion.process_frames(framesPath)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 25, in process_frames
    return self.get_motion_per_time(dict_frame_time)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 82, in get_motion_per_time
    result[dict_pose_startTime[birdPart]][birdPart]:delta
KeyError: 1.0
2022-12-14 23:44:09 INFO     Extract Data source type is: Media
2022-12-14 23:44:09 ERROR    unhashable type: 'dict'
Traceback (most recent call last):
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\Controllers\controllers.py", line 26, in execute
    exec(str(code))
  File "<string>", line 3, in <module>
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\core.py", line 12, in extract
    data = data_source.extract(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\DataSources\Media\Media.py", line 9, in extract
    data = BirdMoveDetect().get_changes(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\BirdMoveDetect.py", line 39, in get_changes
    changes_arr = motion.process_frames(framesPath)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 25, in process_frames
    return self.get_motion_per_time(dict_frame_time)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 52, in get_motion_per_time
    result={{}}
TypeError: unhashable type: 'dict'
2022-12-14 23:44:12 INFO     Extract Data source type is: Media
2022-12-14 23:44:12 ERROR    unhashable type: 'dict'
Traceback (most recent call last):
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\Controllers\controllers.py", line 26, in execute
    exec(str(code))
  File "<string>", line 3, in <module>
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\core.py", line 12, in extract
    data = data_source.extract(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\DataSources\Media\Media.py", line 9, in extract
    data = BirdMoveDetect().get_changes(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\BirdMoveDetect.py", line 39, in get_changes
    changes_arr = motion.process_frames(framesPath)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 25, in process_frames
    return self.get_motion_per_time(dict_frame_time)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 52, in get_motion_per_time
    result={{}}
TypeError: unhashable type: 'dict'
2022-12-14 23:44:12 INFO     Extract Data source type is: Media
2022-12-14 23:44:12 ERROR    unhashable type: 'dict'
Traceback (most recent call last):
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\Controllers\controllers.py", line 26, in execute
    exec(str(code))
  File "<string>", line 3, in <module>
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\core.py", line 12, in extract
    data = data_source.extract(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\DataSources\Media\Media.py", line 9, in extract
    data = BirdMoveDetect().get_changes(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\BirdMoveDetect.py", line 39, in get_changes
    changes_arr = motion.process_frames(framesPath)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 25, in process_frames
    return self.get_motion_per_time(dict_frame_time)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 52, in get_motion_per_time
    result={{}}
TypeError: unhashable type: 'dict'
2022-12-14 23:44:14 INFO     Extract Data source type is: Media
2022-12-14 23:44:14 ERROR    unhashable type: 'dict'
Traceback (most recent call last):
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\Controllers\controllers.py", line 26, in execute
    exec(str(code))
  File "<string>", line 3, in <module>
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\core.py", line 12, in extract
    data = data_source.extract(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\DataSources\Media\Media.py", line 9, in extract
    data = BirdMoveDetect().get_changes(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\BirdMoveDetect.py", line 39, in get_changes
    changes_arr = motion.process_frames(framesPath)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 25, in process_frames
    return self.get_motion_per_time(dict_frame_time)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 52, in get_motion_per_time
    result={{}}
TypeError: unhashable type: 'dict'
2022-12-14 23:44:17 INFO     Extract Data source type is: Media
2022-12-14 23:44:17 ERROR    unhashable type: 'dict'
Traceback (most recent call last):
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\Controllers\controllers.py", line 26, in execute
    exec(str(code))
  File "<string>", line 3, in <module>
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\core.py", line 12, in extract
    data = data_source.extract(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\DataSources\Media\Media.py", line 9, in extract
    data = BirdMoveDetect().get_changes(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\BirdMoveDetect.py", line 39, in get_changes
    changes_arr = motion.process_frames(framesPath)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 25, in process_frames
    return self.get_motion_per_time(dict_frame_time)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 52, in get_motion_per_time
    result={{}}
TypeError: unhashable type: 'dict'
2022-12-14 23:44:17 INFO     Extract Data source type is: Media
2022-12-14 23:44:17 ERROR    unhashable type: 'dict'
Traceback (most recent call last):
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\Controllers\controllers.py", line 26, in execute
    exec(str(code))
  File "<string>", line 3, in <module>
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\core.py", line 12, in extract
    data = data_source.extract(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\DataSources\Media\Media.py", line 9, in extract
    data = BirdMoveDetect().get_changes(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\BirdMoveDetect.py", line 39, in get_changes
    changes_arr = motion.process_frames(framesPath)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 25, in process_frames
    return self.get_motion_per_time(dict_frame_time)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 52, in get_motion_per_time
    result={{}}
TypeError: unhashable type: 'dict'
2022-12-14 23:44:19 INFO     Extract Data source type is: Media
2022-12-14 23:44:19 ERROR    unhashable type: 'dict'
Traceback (most recent call last):
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\Controllers\controllers.py", line 26, in execute
    exec(str(code))
  File "<string>", line 3, in <module>
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\core.py", line 12, in extract
    data = data_source.extract(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\DataSources\Media\Media.py", line 9, in extract
    data = BirdMoveDetect().get_changes(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\BirdMoveDetect.py", line 39, in get_changes
    changes_arr = motion.process_frames(framesPath)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 25, in process_frames
    return self.get_motion_per_time(dict_frame_time)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 52, in get_motion_per_time
    result={{}}
TypeError: unhashable type: 'dict'
2022-12-14 23:44:19 INFO     Extract Data source type is: Media
2022-12-14 23:44:19 ERROR    unhashable type: 'dict'
Traceback (most recent call last):
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\Controllers\controllers.py", line 26, in execute
    exec(str(code))
  File "<string>", line 3, in <module>
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\core.py", line 12, in extract
    data = data_source.extract(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\DataSources\Media\Media.py", line 9, in extract
    data = BirdMoveDetect().get_changes(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\BirdMoveDetect.py", line 39, in get_changes
    changes_arr = motion.process_frames(framesPath)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 25, in process_frames
    return self.get_motion_per_time(dict_frame_time)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 52, in get_motion_per_time
    result={{}}
TypeError: unhashable type: 'dict'
2022-12-14 23:44:19 INFO     Extract Data source type is: Media
2022-12-14 23:44:19 ERROR    unhashable type: 'dict'
Traceback (most recent call last):
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\Controllers\controllers.py", line 26, in execute
    exec(str(code))
  File "<string>", line 3, in <module>
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\core.py", line 12, in extract
    data = data_source.extract(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\DataSources\Media\Media.py", line 9, in extract
    data = BirdMoveDetect().get_changes(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\BirdMoveDetect.py", line 39, in get_changes
    changes_arr = motion.process_frames(framesPath)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 25, in process_frames
    return self.get_motion_per_time(dict_frame_time)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 52, in get_motion_per_time
    result={{}}
TypeError: unhashable type: 'dict'
2022-12-14 23:44:53 INFO     Extract Data source type is: Media
2022-12-14 23:44:53 INFO     Load Data distination type is: Flatfile
2022-12-14 23:59:49 INFO     Extract Data source type is: Media
2022-12-14 23:59:50 INFO     Load Data distination type is: Flatfile
2022-12-15 00:05:30 INFO     Extract Data source type is: Media
2022-12-15 00:05:30 ERROR    0
Traceback (most recent call last):
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\Controllers\controllers.py", line 26, in execute
    exec(str(code))
  File "<string>", line 3, in <module>
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\core.py", line 12, in extract
    data = data_source.extract(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\DataSources\Media\Media.py", line 9, in extract
    data = BirdMoveDetect().get_changes(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\BirdMoveDetect.py", line 39, in get_changes
    changes_arr = motion.process_frames(framesPath)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 25, in process_frames
    return self.get_motion_per_time(dict_frame_time)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 86, in get_motion_per_time
    print(result[0])
KeyError: 0
2022-12-15 00:05:34 INFO     Extract Data source type is: Media
2022-12-15 00:05:34 ERROR    0
Traceback (most recent call last):
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\Controllers\controllers.py", line 26, in execute
    exec(str(code))
  File "<string>", line 3, in <module>
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\core.py", line 12, in extract
    data = data_source.extract(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\DataSources\Media\Media.py", line 9, in extract
    data = BirdMoveDetect().get_changes(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\BirdMoveDetect.py", line 39, in get_changes
    changes_arr = motion.process_frames(framesPath)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 25, in process_frames
    return self.get_motion_per_time(dict_frame_time)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 86, in get_motion_per_time
    print(result[0])
KeyError: 0
2022-12-15 00:05:36 INFO     Extract Data source type is: Media
2022-12-15 00:05:36 ERROR    0
Traceback (most recent call last):
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\Controllers\controllers.py", line 26, in execute
    exec(str(code))
  File "<string>", line 3, in <module>
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\core.py", line 12, in extract
    data = data_source.extract(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\DataSources\Media\Media.py", line 9, in extract
    data = BirdMoveDetect().get_changes(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\BirdMoveDetect.py", line 39, in get_changes
    changes_arr = motion.process_frames(framesPath)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 25, in process_frames
    return self.get_motion_per_time(dict_frame_time)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 86, in get_motion_per_time
    print(result[0])
KeyError: 0
2022-12-15 00:05:37 INFO     Extract Data source type is: Media
2022-12-15 00:05:37 ERROR    0
Traceback (most recent call last):
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\Controllers\controllers.py", line 26, in execute
    exec(str(code))
  File "<string>", line 3, in <module>
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\core.py", line 12, in extract
    data = data_source.extract(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\DataSources\Media\Media.py", line 9, in extract
    data = BirdMoveDetect().get_changes(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\BirdMoveDetect.py", line 39, in get_changes
    changes_arr = motion.process_frames(framesPath)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 25, in process_frames
    return self.get_motion_per_time(dict_frame_time)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 86, in get_motion_per_time
    print(result[0])
KeyError: 0
2022-12-15 00:05:37 INFO     Extract Data source type is: Media
2022-12-15 00:05:37 ERROR    0
Traceback (most recent call last):
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\Controllers\controllers.py", line 26, in execute
    exec(str(code))
  File "<string>", line 3, in <module>
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\core.py", line 12, in extract
    data = data_source.extract(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\DataSources\Media\Media.py", line 9, in extract
    data = BirdMoveDetect().get_changes(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\BirdMoveDetect.py", line 39, in get_changes
    changes_arr = motion.process_frames(framesPath)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 25, in process_frames
    return self.get_motion_per_time(dict_frame_time)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 86, in get_motion_per_time
    print(result[0])
KeyError: 0
2022-12-15 00:05:38 INFO     Extract Data source type is: Media
2022-12-15 00:05:38 ERROR    0
Traceback (most recent call last):
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\Controllers\controllers.py", line 26, in execute
    exec(str(code))
  File "<string>", line 3, in <module>
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\core.py", line 12, in extract
    data = data_source.extract(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\DataSources\Media\Media.py", line 9, in extract
    data = BirdMoveDetect().get_changes(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\BirdMoveDetect.py", line 39, in get_changes
    changes_arr = motion.process_frames(framesPath)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 25, in process_frames
    return self.get_motion_per_time(dict_frame_time)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 86, in get_motion_per_time
    print(result[0])
KeyError: 0
2022-12-15 00:05:42 INFO     Extract Data source type is: Media
2022-12-15 00:05:42 ERROR    0
Traceback (most recent call last):
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\Controllers\controllers.py", line 26, in execute
    exec(str(code))
  File "<string>", line 3, in <module>
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\core.py", line 12, in extract
    data = data_source.extract(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\DataSources\Media\Media.py", line 9, in extract
    data = BirdMoveDetect().get_changes(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\BirdMoveDetect.py", line 39, in get_changes
    changes_arr = motion.process_frames(framesPath)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 25, in process_frames
    return self.get_motion_per_time(dict_frame_time)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 86, in get_motion_per_time
    print(result[0])
KeyError: 0
2022-12-15 00:05:55 INFO     Extract Data source type is: Media
2022-12-15 00:05:55 ERROR    0
Traceback (most recent call last):
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\Controllers\controllers.py", line 26, in execute
    exec(str(code))
  File "<string>", line 3, in <module>
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\core.py", line 12, in extract
    data = data_source.extract(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\etl\DataSources\Media\Media.py", line 9, in extract
    data = BirdMoveDetect().get_changes(file_path)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\BirdMoveDetect.py", line 39, in get_changes
    changes_arr = motion.process_frames(framesPath)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 25, in process_frames
    return self.get_motion_per_time(dict_frame_time)
  File "c:\Users\rhaze\Desktop\Projects\ETLV2\app\bird_cv\motionDetection\motion.py", line 86, in get_motion_per_time
    print(result[0])
KeyError: 0
2022-12-15 00:07:41 INFO     Extract Data source type is: Media
2022-12-15 00:07:41 INFO     Load Data distination type is: Flatfile
2022-12-15 00:08:48 INFO     Extract Data source type is: Media
2022-12-15 00:08:49 INFO     Load Data distination type is: Flatfile
2022-12-15 00:11:12 INFO     Extract Data source type is: Media
2022-12-15 00:11:13 INFO     Load Data distination type is: Flatfile
2022-12-15 00:11:48 INFO     Extract Data source type is: Media
2022-12-15 00:11:48 INFO     Load Data distination type is: Flatfile
2022-12-15 00:13:25 INFO     Extract Data source type is: Media
2022-12-15 00:13:26 INFO     Load Data distination type is: Flatfile
2022-12-15 00:16:58 INFO     Extract Data source type is: Media
2022-12-15 00:16:58 INFO     Load Data distination type is: Flatfile
2022-12-15 00:22:48 INFO     Extract Data source type is: Media
2022-12-15 00:22:48 INFO     Load Data distination type is: Flatfile
2022-12-15 00:25:08 INFO     Extract Data source type is: Media
2022-12-15 00:25:08 INFO     Load Data distination type is: Flatfile
